version: "{build}"

skip_tags: true
test: off
max_jobs: 1

install:
  - cmd: SET MINGW_DIR=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1
  - cmd: SET PATH=%MINGW_DIR%\mingw32\bin;%PATH%
  
before_build:
  - cmd: mingw32-make --version | head -1
  - cmd: g++ --version | head -1
  - cmd: 7z --help | head -3
  - cmd: git symbolic-ref HEAD

build_script:
  - cmd: cd "build\mingw"
  - cmd: mingw32-make

matrix:
  fast_finish: true

deploy:
  - provider: Environment
    name: GH
    on:
      branch: filevars
