version: "{build}"

skip_tags: true
test: off
max_jobs: 1

install:
  - cmd: FOR /F "delims=" %%a IN ('python build\mingw\appveyor_mingw.py') DO SET MINGW_DIR=%%a
  - cmd: IF "."=="%MINGW_DIR%" ( EXIT 404 )
  - cmd: SET PATH=%MINGW_DIR%\mingw64\bin;%PATH%

before_build:
  - cmd: mingw32-make --version | head -1
  - cmd: g++ --version | head -1
  - cmd: 7z --help | head -3

build_script:
  - cmd: CD build\mingw
  - cmd: mingw32-make

after_build:
  - cmd: MKDIR ..\..\deploy
  - cmd: CD ..\..\deploy
  - cmd: COPY ..\build\mingw\Notepad2.exe .
  - cmd: COPY ..\Notepad2.ini .
  - cmd: COPY ..\Notepad2.txt .
  - cmd: COPY ..\Readme.txt .
  - cmd: COPY ..\Readme-mod.txt .
  - cmd: COPY ..\Readme.md .
  - cmd: COPY ..\License.txt .
  - cmd: ECHO https://github.com/%APPVEYOR_REPO_NAME%/tree/%APPVEYOR_REPO_BRANCH%> %APPVEYOR_PROJECT_NAME%-%APPVEYOR_BUILD_NUMBER%.txt
  - cmd: 7z a ..\%APPVEYOR_PROJECT_NAME%-%APPVEYOR_BUILD_NUMBER%.7z .

artifacts:
  - path: $(appveyor_project_name)-$(appveyor_repo_branch)-$(appveyor_build_number).7z

matrix:
  fast_finish: true

deploy:
  - provider: Environment
    name: appveyor-releases
    on:
      branch: next-av

  - provider: Environment
    name: GH
    on:
      branch: next-av
